### PR TITLE
#159129933 Build  out  Get all entries endpoint

### PR DESCRIPTION
**Pull request by kelvinrandu**
What does this PR do?

The PR builds out the GET  /api/v1/entries.

What does it do?
it is meant to retrieve all diary entries from entries dictionary

Below is a link to the relevant story on pivotal tracker

https://www.pivotaltracker.com/story/show/159129933

allentry

### CODE REVIEW

**Comment by YAHYA-H** [comment]
PLEASE IGNORE YOUR VENV FILES!!

**Comment by YAHYA-H** [comment]
nice :+1: :100:

**Comment by SrMoffat** [comment]
Nice work bro....the endpoint seems to work ok. The build is passing. Nice

**Comment by charisschomba** [comment]
Nice work

**Pull request merged**
